name: CordCloud

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: WeiZhenOoooo/cordcloud-action@main
        with:
          EMAIL: ${{ secrets.CC_EMAIL }}          # 改为大写
          PASSWD: ${{ secrets.CC_PASSWD }}        # 改为大写
          IMAP_SERVER: ${{ secrets.CC_IMAP_SERVER }}  # 改为大写
          AUTH_CODE: ${{ secrets.CC_AUTH_CODE }}      # 改为大写